app/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from tastypie.api import Api
from app.views import custom_admin_views as views
from app.views import common_views as c_views
from app.views import api_v1_custom_views as v1_views
from app.models import OrderedProduct, OfferLocationMapping
from app import resources

v1_api = Api(api_name='v1')

v1_api.register(resources.ServiceResource())
v1_api.register(resources.CategoryResource())
v1_api.register(resources.AddressResource())
v1_api.register(resources.UserResource())
v1_api.register(resources.LocationResource())
v1_api.register(resources.StoreResource())
v1_api.register(resources.SizeResource())
v1_api.register(resources.ProductResource())
v1_api.register(resources.ProductSizeImageResource())
v1_api.register(resources.StoreProductResource())
v1_api.register(resources.AvailableServiceResource())
v1_api.register(resources.OrderResource())
v1_api.register(resources.CartResource())
v1_api.register(resources.CouponResource())
v1_api.register(resources.ProductsPerCategory())
v1_api.register(resources.OrderedProductResource())
v1_api.register(resources.SuggestionResource())
v1_api.register(resources.OrderStatusResource())
v1_api.register(resources.OfferResource())
v1_api.register(resources.OfferLocationResource())
v1_api.register(resources.OfferProductResource())
v1_api.register(resources.OfferProductOrderResource())
v1_api.register(resources.VisitorResource())
v1_api.register(resources.TagResource())

admin.site.login = views.admin_login

urlpatterns = patterns('',

    #common
    url(r'^$', c_views.web_site_page, name='web_site_page'),
    url(r'^bill/$', c_views.bill, name='bill'),
    url(r'^validate_txn/$', c_views.validate_txn, name='validate_txn'),
    url(r'^android/$', c_views.android_app_redirection,name='android_app_redirection'),
    url(r'^app_version_code/$', c_views.appversioncode,name='appversioncode'),

    #v2
    url('api/v2/', include('app.api_v2_urls')),

    #v1
    url(r'^api/v1/store_product/$',v1_views.get_store_products,name="get_store_products"),
    url(r'^api/v1/available_services/$',v1_views.get_available_services,name="get_available_services"),
    url(r'^api/v1/products_per_cat/set/(?P<ids>.*)/$',v1_views.get_products_per_category,name="get_products_per_category"),
    url(r'^api/v1/$', views.blank),
    url(r'^.*/schema/$', views.blank),
    (r'^api/', include(v1_api.urls)),

    #django admin
    url(r'^admin/app/store/$', views.show_stores, name='show_stores'),
    url(r'^admin/app/storeproductmapping/add/', views.add_product, name='add_product'),
    url(r'^admin/app/location/add/',views.add_new_location, name='add_new_location'),
    url(r'^admin/app/storeproductmapping/$',views.show_list_storeproduct, name='show_list_storeproduct'),
    url(r'^admin/app/offer/$', views.show_offers, name='show_offers'),
    url(r'^admin/', include(admin.site.urls)),

    #custom admin
    url('movinCartAdmin/', include('app.custom_admin_urls')),

    #custom api v1
    url('app/', include('app.custom_app_urls')),
)

movincart/urls.py
from django.conf.urls import patterns, include, url
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'movincart.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url('', include('app.urls')),
)

app/models.py
import threading
from django.contrib.auth.models import User
from django.db import models
from django.contrib.gis.db.models import PolygonField
from geoposition.fields import GeopositionField
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.core.mail import send_mail
from django.conf import settings
import datetime as dt
import simplejson
from tastypie.authentication import ApiKeyAuthentication
from tastypie.models import create_api_key, ApiKey
from app.utils import constant



class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract =True

class Location(BaseModel):
    city = models.CharField(max_length=100)
    zone = models.CharField(max_length=100,default="")
    area = models.CharField(max_length=100)
    sub_area = models.CharField(max_length=100)
    mpoly = PolygonField()

    class Meta:
        unique_together = ('city', 'zone','area','sub_area',)

    def __unicode__(self):
        return self.sub_area+", "+self.area

class TimeSlot(BaseModel):

    start_time = models.TimeField()
    end_time = models.TimeField()
    def __unicode__(self):
        return str(self.start_time)+" to "+str(self.end_time)

    class Meta:
        unique_together = ('start_time', 'end_time',)


class UserProfile(BaseModel):
    user = models.OneToOneField(User)
    contact = models.BigIntegerField()
    app_id=models.CharField(max_length=250, blank=True, null=True)
    app_version=models.CharField(max_length=10, blank=True, null=True)
    device_id=models.CharField(max_length=300, blank=True, null=True)
    otp=models.CharField(max_length=100, blank=True, null=True)

    def __unicode__(self):
        return self.user.email


class Address(BaseModel):
    user = models.ForeignKey(User)
    address = models.CharField(max_length=500)
    landmark = models.CharField(max_length=150)
    location_show = models.CharField(max_length=500)
    location = models.ForeignKey(Location)
    is_default = models.BooleanField(default=False)

    def __unicode__(self):
        return self.address+' '+self.landmark+' '+ self.location_show + self.location.sub_area + self.location.area


class Service(BaseModel):
    name = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True)
    image = models.ImageField(upload_to="/media/")
    def __unicode__(self):
        return self.name


class Store(BaseModel):
    
    name = models.CharField(max_length=100)
    owner_name = models.CharField(max_length=100)
    contact = models.TextField()
    address = models.CharField(max_length=1000L)
    position = GeopositionField(blank=True, default='19.101985614850385, 72.88626194000244')
    rating = models.IntegerField(default=0)
    open_time = models.TimeField()
    end_time = models.TimeField()
    is_active=models.BooleanField(default=True)

    backup_shops = models.ManyToManyField('self', blank=True, null=True)

    rush_hours = models.ManyToManyField(TimeSlot,related_name='rush_hour')
    normal_hours = models.ManyToManyField(TimeSlot,related_name='normal_hour')


    services = models.ManyToManyField(Service)
    weekly_off = models.IntegerField(default = -1)

    def __unicode__(self):
        return self.name



class LocationServiceMapping(BaseModel):

    service= models.ForeignKey(Service)
    location=models.ForeignKey(Location)
    stores = models.ManyToManyField(Store,null=True, through='StoreTimingInLocation',related_name='stores')

    is_active=models.BooleanField(default=True)
    is_coming_soon = models.BooleanField(default=False)
    display_order = models.IntegerField(default=0)



    def __unicode__(self):
        return self.service.name

    class Meta:
        unique_together = ('service', 'location',)

    def save(self, *args, **kwargs):

        # if self.stores.all().count()>=1:
        #     raise ValueError(str('Can Not Add Multiple Store for single service location mapping'))

        super(LocationServiceMapping, self).save(*args, **kwargs)


class StoreTimingInLocation(BaseModel):

    store = models.ForeignKey(Store)
    time_slot = models.ManyToManyField(TimeSlot)
    lsm = models.ForeignKey(LocationServiceMapping)

    delivery_charges = models.IntegerField(default=0)
    delivery_min_amount = models.IntegerField(default=0)
    normal_hours_delivery_time_min = models.IntegerField(default=60, help_text="Time in Minutes")
    rush_hours_delivery_time_min = models.IntegerField(default=60, help_text="Time in Minutes")

    is_active=models.BooleanField(default=True)
    def save(self, *args, **kwargs):
        def check_overlap(t1_all,t2_all):
            for t1 in t1_all:
                for t2 in t2_all:
                    latest_start=max(t1.start_time,t2.start_time)
                    earliest_end = min(t2.end_time,t1.end_time)
                    if latest_start<earliest_end:
                        return True
            return False
        other_stores = filter(lambda x: check_overlap(x.time_slot.all(),self.time_slot.all()),StoreTimingInLocation.objects.filter(lsm=self.lsm,is_active=True).exclude(store=self.store))
        if other_stores and self.is_active:
            raise ValueError(str('Something is wrong with your mind!! Can Not Add Multiple Store for '+str(self.lsm.service)+" in "+str(self.lsm.location)))
        super(StoreTimingInLocation, self).save(*args, **kwargs)
    class Meta:
        unique_together = ('store','lsm',)

class Size(BaseModel):
    
    unit = models.CharField(max_length=100)
    magnitude =models.FloatField()
    description = models.CharField(max_length=500,default="")

    def __unicode__(self):
        return str(self.magnitude)+" "+self.unit

class Category(BaseModel):
    name = models.CharField(max_length=200)
    service = models.ForeignKey(Service)
    parent = models.ForeignKey('self', blank=True,null=True)
    display_order = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    
    def __unicode__(self):
        return self.name

    def save(self, *args, **kw):
        serv = self.service
        par = self.parent
        if par:
            if par.service!= serv:
                raise ValueError(str('Entered Service and Parent Category Not Valid'))
        super(Category, self).save(*args, **kw)
        sub_cats = Category.objects.filter(parent=self)
        for s in sub_cats:
            print s.name
            s.service=self.service
            s.save()



class Tag(BaseModel):
    name = models.CharField(max_length=400)
    def __unicode__(self):
        return self.name

class SubSubCategory(BaseModel):

    name = models.CharField(max_length=255)
    sub_category = models.ForeignKey(Category)

    def save(self, *args, **kwargs):
        if not self.sub_category.parent:
            raise ValueError(str('invalid sub-category'))
        super(SubSubCategory, self).save(*args, **kwargs)




class Product(BaseModel):
    
    name = models.CharField(max_length=255)
    brand_name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, limit_choices_to={'parent__gte': 1}, verbose_name="Sub Category")
    tags = models.ManyToManyField(Tag,blank=True,null=True)
    rating = models.IntegerField(default=0)
    barcode = models.TextField(blank=True, null=True)
    related_products = models.ManyToManyField('self',blank=True,null=True)

    sub_sub_category = models.ForeignKey(SubSubCategory,null=True)

    def __unicode__(self):
        return self.name


class ProductSizeImageMapping(BaseModel):
    product = models.ForeignKey(Product)
    size = models.ForeignKey(Size)
    image = models.ImageField(upload_to="/media/")
    is_basic_product = models.BooleanField(default=False)
    def __unicode__(self):
        return self.product.name

    def xs_image(self):
        return str(self.image).replace('/m/','/xs/')

    class Meta:
        unique_together = ('product', 'size',)


class StoreProductMapping(BaseModel):

    product = models.ForeignKey(ProductSizeImageMapping)
    store = models.ForeignKey(Store)

    price = models.FloatField(null=True, blank=True)
    price_to_movincart = models.FloatField(null=True, blank=True)
    discount = models.FloatField(default=0)

    stock = models.BooleanField(default=True)
    display_order = models.IntegerField(default=0)
    max_buy = models.IntegerField(default=20)
    freebies_list = models.CharField(max_length=100,blank=True,null=True)

    def __unicode__(self):
        return self.product.product.name+' '+str(self.product.size)+' '+str(self.price)

    def save(self, *args, **kwargs):
        if self.price==0 and self.stock:
            raise ValueError(str('Please add a price >0'))
        super(StoreProductMapping, self).save(*args, **kwargs)

    class Meta:

        unique_together = ('product', 'store',)
        permissions = (
            ("can_download_product_dump", "Can download products dump"),
        )

class StoreProductChanged(BaseModel):
    product = models.ForeignKey(StoreProductMapping)


class CouponRuleBook(BaseModel):

    MIN_TOTAL = 0 # minimum order total
    SERVICE_TYPE = 1 # Single Service or multi service or ALL services
    SERVICE_VALUE = 2 # Service ID for coupon Applied
    UNIVERSAL = 3 # universal if anyone can use this coupon anytime.. new_user if only new user can use coupon .. user_specific only one user can use this coupon
    USER_SPECIFIC =4 # username of user
    MAX_USE_NUMBER =5 # max use count
    LOCATION = 6 #
    CATEGORY = 7 #
    IGNORE_CATEGORY = 8 #
    VERSION_NUMBER = 9
    OFFER_USED_USER_CAN_USE =10
    CHOICES = ((MIN_TOTAL,'Minimum Total'),(SERVICE_TYPE,'Service Type'),(SERVICE_VALUE,'Service ID for Coupon'),(UNIVERSAL,'Universal'),(USER_SPECIFIC,'Username '),(MAX_USE_NUMBER,'Max Use Number'),

templates/new_custom_admin/v2/order_status.html
{% extends "new_custom_admin/base.html" %}
{% load static %}
{% block bodycontent %}
<link rel="stylesheet" href="{% static "jquery/json_viewer/css/jjsonviewer.css"%}">
<div class="page coupon-single-coupon-page">
	<div class="pageheader">
		<h2 class="page-header">Test API</h2>
		<div class="page-bar">
			<ul class="page-breadcrumb">
				<li>
					<a href="/movinCartAdmin/"><i class="fa fa-home"></i> MovinCart</a>
				</li>
				<li>
					<a href="order_status">Order Status API Detail</a>
				</li>
			</ul>
		</div>
	</div>
	<div class="add-nav">
		<div role="tabpanel">
			<!-- Nav tabs -->
			<div class="tab-content">
				<!-- tab in tabs -->
				<div role="tabpanel" class="tab-pane active" id="details">
					<!-- row -->
					<div class="row">
						<!-- col -->
						<div class="col-md-12">
							<!-- tile -->
							<form action="" method="GET" id="myForm" class="form-horizontal ng-pristine ng-valid" role="form">
								{% csrf_token %}
								<section class="tile">
									<!-- tile header -->
									<div class="tile-header dvd dvd-btm">
										<h1 class="custom-font"><strong>Order Status API Details </strong></h1>
									</div>
									<!-- /tile header -->
									<!-- tile body -->
									<div class="form-group">
										<label for="user" class="col-sm-2 control-label">Contact: <span class="text-lightred text-md"></span></label>
										<div class="col-sm-6">
											<select tabindex="1" name="contact" id="id_contact"  class="chosen-select" style="width: 93%;" >
												<option value="">--------------------</option>
												{% if userprofile %}
												{% for l in userprofile %}
												<option value="{{l.contact}}" >{{l.contact}}</option>
												{% endfor %}
												{% endif %}
											</select>
										</div>
									</div>
									<ul class="pager">
										<li>
											<a href="#" onclick="validate_n_submit()" class="btn btn-ef btn-ef-1 btn-ef-1-success btn-ef-1b mb-10" data-toggle="tooltip" title="Save"><i>Submit</i></a>
										</li>
									</ul>
								</section>
							</form>
                         </div>
                      </div>
                  </div>
			</div>
		</div>
	</div>
	<div class="tile-body" id="image_div" ></div>
	<div id = "placeholder"></div>
</div>
{% endblock %}
{% block jscontent %}
<script src="{% static "jquery/json_viewer/js/jjsonviewer.js"%}"></script>

<script>
function validate_n_submit() {

	$(document).ready(function(){
	    document.getElementById("image_div").innerHTML='<img src="{% static "ajax-loader.gif"%}"  style="padding-top:17px;padding-bottom:17px;margin-left: 48%;"/>';
		$(document).ajaxStart(function(){
			$("#image_div").css("display", "block");
		});
		$(document).ajaxComplete(function(){
			$("#image_div").css("display", "none");
		});
		var contact=document.getElementById("id_contact").value;
		var url ="/api/v2/order_status/?api_key=205b784b88c766e8955820753ec32b4eb53ac87d&username="+contact;
		$.getJSON(url,function(data)
		{
			$("#placeholder").jJsonViewer(data);
		});
	});
}
</script>
{% endblock %}

templates/new_custom_admin/v2/product_per_cat.html
{% extends "new_custom_admin/base.html" %}
{% load static %}
{% block bodycontent %}
<link rel="stylesheet" href="{% static "jquery/json_viewer/css/jjsonviewer.css"%}">
<div  class="page coupon-single-coupon-page">
	<div class="pageheader">
		<h2 class="page-header">Test API</h2>
		<div class="page-bar">
			<ul class="page-breadcrumb">
				<li>
					<a href="/movinCartAdmin/"><i class="fa fa-home"></i> MovinCart</a>
				</li>
				<li>
					<a href="#">Product Per Category  API Detail</a>
				</li>
			</ul>
		</div>
	</div>
	<div class="add-nav">
		<div role="tabpanel">
			<!-- Nav tabs -->
			<div class="tab-content">
				<!-- tab in tabs -->
				<div role="tabpanel" class="tab-pane active" id="details">
					<!-- row -->
					<div class="row">
						<!-- col -->
						<div class="col-md-12">
							<!-- tile -->
							<form action="" method="GET" id="myForm" class="form-horizontal ng-pristine ng-valid" role="form">
								{% csrf_token %}
								<section class="tile">
									<!-- tile header -->
									<div class="tile-header dvd dvd-btm">
										<h1 class="custom-font"><strong>Product Per Category API Details </strong></h1>
									</div>
									<!-- /tile header -->
									<!-- tile body -->
									<div class="form-group">
										<label for="locations" class="col-sm-2 control-label">Location ID: <span class="text-lightred text-md"></span></label>
										<div class="col-sm-6">
											<select tabindex="1" name="location" id="id_location"  class="chosen-select" style="width: 93%;" >
												<option value="">--------------------</option>
												{% for l in locations %}
												<option value="{{l.id}}" >{{l.sub_area}}</option>
												{% endfor %}
											</select>
										</div>
									</div>
									<div class="form-group">
										<label for="category" class="col-sm-2 control-label">Category: <span class="text-lightred text-md"></span></label>
										<div class="col-sm-6">
											<select tabindex="1" multiple name="location" id="id_category"  class="chosen-select" style="width: 93%;" >
												<option value="">--------------------</option>
												{% for l in category %}
												<option value="{{l.id}}" >{{l.name}}</option>
												{% endfor %}
											</select>
										</div>
									</div>
									<ul class="pager">
										<li>
											<a href="#" onclick="validate_n_submit()" class="btn btn-ef btn-ef-1 btn-ef-1-success btn-ef-1b mb-10" data-toggle="tooltip" title="Save"><i>Submit</i></a>
										</li>
									</ul>
								</section>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="tile-body" id="image_div" ></div>
	<div id = "placeholder"></div>
</div>
{% endblock %}
{% block jscontent %}

<script src="{% static "jquery/json_viewer/js/jjsonviewer.js"%}"></script>

<script>

function validate_n_submit() {

	var a=document.getElementById("id_location").value;
	var selected=$('#id_category').val();
	var b = selected.join(";");
	var url ='/api/v2/products_per_cat/?category_ids='+b+'&location='+5;
	$(document).ready(function(){
		    document.getElementById("image_div").innerHTML='<img src="{% static "ajax-loader.gif"%}"  style="padding-top:17px;padding-bottom:17px;margin-left: 48%;"/>';
		$(document).ajaxStart(function(){
			$("#wait").css("display", "block");
		});
		$(document).ajaxComplete(function(){
			$("#wait").css("display", "none");
		});
		$.getJSON(url,function(data){
			$("#placeholder").jJsonViewer(data);
		});
	});
}
</script>
{% endblock %}

templates/new_custom_admin/v2/search_product.html
{% extends "new_custom_admin/base.html" %}
{% load static %}
{% block bodycontent %}
<link rel="stylesheet" href="{% static "jquery/json_viewer/css/jjsonviewer.css"%}"> 0
<div class="page coupon-single-coupon-page">
	<div class="pageheader">
		<h2 class="page-header">Test API</h2>
		<div class="page-bar">
			<ul class="page-breadcrumb">
				<li>
					<a href="/movinCartAdmin/"><i class="fa fa-home"></i> MovinCart</a>
				</li>
				<li>
					<a href="#">Search Product API Detail</a>
				</li>
			</ul>
		</div>
	</div>
	<div class="add-nav">
		<div role="tabpanel">
			<!-- Nav tabs -->
			<div class="tab-content">
				<!-- tab in tabs -->
				<div role="tabpanel" class="tab-pane active" id="details">
					<!-- row -->
					<div class="row">
						<!-- col -->
						<div class="col-md-12">
							<!-- tile -->
							<form action="" method="GET" id="myForm" class="form-horizontal ng-pristine ng-valid" role="form">
								{% csrf_token %}
								<section class="tile">
									<!-- tile header -->
									<div class="tile-header dvd dvd-btm">
										<h1 class="custom-font"><strong>Search Product API Details </strong></h1>
									</div>
									<!-- /tile header -->
									<!-- tile body -->
									<div class="form-group">
										<label for="locations" class="col-sm-2 control-label">Location ID: <span class="text-lightred text-md"></span></label>
										<div class="col-sm-6">
											<select tabindex="1" name="location" id="id_location"  class="chosen-select" style="width: 95%;" >
												<option value="">--------------------</option>
												{% for l in locations %}
												<option value="{{l.id}}" >{{l.sub_area}}</option>
												{% endfor %}
											</select>
										</div>
                                       </div>
									<div class="form-group">
										<label for="p_name" class="col-sm-2 control-label">Search: <span class="text-lightred text-md">*</span></label>
										<div class="col-sm-6">
											<input required name="p_name" type="value"  class="form-control" id="id_name" placeholder="Search" style="width:100%">
                                            </div>
                                        </div>
									<ul class="pager">
										<li>
											<a href="#" onclick="validate_n_submit()" class="btn btn-ef btn-ef-1 btn-ef-1-success btn-ef-1b mb-10" data-toggle="tooltip" title="Save"><i>Submit</i></a>
										</li>
									</ul>
								</section>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="tile-body" id="image_div" ></div>
		<div id = "placeholder"></div>
	</div>
</div>
{% endblock %}
{% block jscontent %}

<script src="{% static "jquery/json_viewer/js/jjsonviewer.js"%}"></script>

<script>

function validate_n_submit()
{
	var a=document.getElementById("id_location").value;
	var b=document.getElementById("id_name").value;
	var r= b.split(" ");
	final_text =''
	for (var m in r) {
		m =r[m] +'+';
		final_text += m;
	}
	final_text = final_text.substring(0, final_text.length-1);
	var url = '/api/v2/get_store_product/?location='+a+'&keyword='+final_text;
	$(document).ready(function(){
		document.getElementById("image_div").innerHTML='<img src="{% static "ajax-loader.gif"%}"  style="padding-top:17px;padding-bottom:17px;margin-left: 48%;"/>';
		$(document).ajaxStart(function(){
			$("#wait").css("display", "block");
		});
		$(document).ajaxComplete(function(){
			$("#wait").css("display", "none");
		});
		$.getJSON(url,function(data){
			$("#placeholder").jJsonViewer(data);
		});
	});
}
</script>
{% endblock %}

templates/new_custom_admin/v2/sub_category.html
{% extends "new_custom_admin/base.html" %}
{% load static %}
{% block bodycontent %}
<link rel="stylesheet" href="{% static "jquery/json_viewer/css/jjsonviewer.css"%}">
<div class="page coupon-single-coupon-page">
	<div class="pageheader">
		<h2 class="page-header">Test API</h2>
		<div class="page-bar">
			<ul class="page-breadcrumb">
				<li>
					<a href="/movinCartAdmin/"><i class="fa fa-home"></i> MovinCart</a>
				</li>
				<li>
					<a href="#">Product for Sub Category API Detail</a>
				</li>
			</ul>
		</div>
	</div>
	<div class="add-nav">
		<div role="tabpanel">
			<!-- Nav tabs -->
			<div class="tab-content">
                  <!-- tab in tabs -->
				<div role="tabpanel" class="tab-pane active" id="details">
					<!-- row -->
					<div class="row">
						<!-- col -->
						<div class="col-md-12">
							<!-- tile -->
							<form action="" method="GET" id="myForm" class="form-horizontal ng-pristine ng-valid" role="form">
								{% csrf_token %}
								<secton class="tile">
									<!-- tile header -->
									<div class="tile-header dvd dvd-btm">
										<h1 class="custom-font"><strong>Product for Sub Category API Details </strong></h1>
									</div>
									<!-- /tile header -->
									<!-- tile body -->
									<div class="form-group">
										<label for="locations" class="col-sm-2 control-label">Location : <span class="text-lightred text-md"></span></label>
										<div class="col-sm-6">
											<select tabindex="1" name="location" id="id_location"  class="chosen-select" style="width: 93%;" >
												<option value="">--------------------</option>
												{% for l in locations %}
												<option value="{{l.id}}" >{{l.sub_area}}</option>
												{% endfor %}
											</select>
										</div>
									</div>
									<div class="form-group">
										<label for="subcategory" class="col-sm-2 control-label">Category: <span class="text-lightred text-md"></span></label>
										<div class="col-sm-6">
											<select tabindex="1" name="subcategory" id="id_category"  class="chosen-select" style="width: 93%;" >
												<option value="">--------------------</option>
												{% for l in subcategory %}
												<option value="{{l.id}}" >{{l.name}}</option>
												{% endfor %}
											</select>
										</div>
									</div>
									<ul class="pager">
										<li>
											<a href="#" onclick="validate_n_submit()" class="btn btn-ef btn-ef-1 btn-ef-1-success btn-ef-1b mb-10" data-toggle="tooltip" title="Save"><i>Submit</i></a>
										</li>
									</ul>
								</secton>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="tile-body" id="image_div" ></div>
	<div id = "placeholder"></div>
</div>
{% endblock %}
{% block jscontent %}

<script src="{% static "jquery/json_viewer/js/jjsonviewer.js"%}"></script>
<script>
function validate_n_submit()
{
	var a=document.getElementById("id_location").value;
	var b=document.getElementById("id_category").value;
	var url = '/api/v2/get_store_product/?location='+5+ '&category='+b
	$(document).ready(function(){
	document.getElementById("image_div").innerHTML='<img src="{% static "ajax-loader.gif"%}"  style="padding-top:17px;padding-bottom:17px;margin-left: 48%;"/>';
		$(document).ajaxStart(function(){
			$("#image_div").css("display", "block");
		});
		$(document).ajaxComplete(function(){
			$("#image_div").css("display", "none");
		});
		$.getJSON(url,function(data){
			$("#placeholder").jJsonViewer(data);
		});
	});
}
</script>
{% endblock %}